### ISSUE TITLE
join missing the 'on' filter

### ISSUE THREAD

**Issue by zhang245606** [JSQLParser/JSqlParser#1229] opened 2021-06-16 03:22 UTC
original SQL : select t1.column1,t1.column2,t2.field1,t2.field2 from T_DT_ytb_01 t1 , T_DT_ytb_02 t2 on t1.column1 = t2.field1
after parse SQL:   SELECT t1.column1, t1.column2, t2.field1, t2.field2 FROM T_DT_ytb_01 t1, T_DT_ytb_02 t2

What is simple join?

**Comment by manticore-projects** [comment] 2021-06-16 03:32
Greetings.

1) I can not confirm your observation. Statement is parsed and deparsed correctly:
```sql
SELECT  t1.column1
        , t1.column2
        , t2.field1
        , t2.field2
FROM t_dt_ytb_01 t1
    , t_dt_ytb_02 t2
        ON t1.column1 = t2.field1
;
```
You an also [test it online here](jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsBcCMA6AxgewDYFcC2AdkgFDxlkA0iqmuhATKeZYvSgGYCWAplgCYlmLBGy68+jAGIAlAPIBZRAH0+CJQE8EAIyUAGJNSbwqa1Ru176rI81kA5aumz4isALysOPfiQDcQA+)

2) Your statement should be invalid though because you should be able to use `ON` only in conjunction with `JOIN`, otherwise you would need to use `WHERE` (at least this is my understanding).

Please double check and close this issue, when confirmed.

**Comment by wumpz** [comment] 2021-06-16 05:29
It could be, like using parseExpressions, that JSqlParser parses as far as it is able to interpret your sql and stops then. How to you parse this statement actually?

**Comment by zhang245606** [comment] 2021-06-16 05:51
> Greetings.
> 
> 1. I can not confirm your observation. Statement is parsed and deparsed correctly:
> 
> ```sql
> SELECT  t1.column1
>         , t1.column2
>         , t2.field1
>         , t2.field2
> FROM t_dt_ytb_01 t1
>     , t_dt_ytb_02 t2
>         ON t1.column1 = t2.field1
> ;
> ```
> 
> You can also [test it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsBcCMA6AxgewDYFcC2AdkgFDxlkA0iqmuhATKeZYvSgGYCWAplgCYlmLBGy68+jAGIAlAPIBZRAH0+CJQE8EAIyUAGJNSbwqa1Ru176rI81kA5aumz4isALysOPfiQDcQA+)
> 
> 1. Your statement should be invalid though because you should be able to use `ON` only in conjunction with `JOIN`, otherwise you would need to use `WHERE` (at least this is my understanding).
> 
> Please double check and close this issue, when confirmed.

**Comment by zhang245606** [comment] 2021-06-16 06:10
Thank you for your reply！

I try to parse it as follows ：
`String sql = "select t1.column1,t1.column2,t2.field1,t2.field2 from T_DT_ytb_01 t1 , T_DT_ytb_02 t2 on t1.column1 = t2.field1";`
`Statement parse = CCJSqlParserUtil.parse(sql);`
`return parse.toString();`


This sql is equivalent to “select t1.column1,t1.column2,t2.field1,t2.field2 from T_DT_ytb_01 t1 inner join T_DT_ytb_02 t2 on t1.column1 = t2.field1”

I don't understand what simple join means .
The debug screenshot is as follows：
![image](https://user-images.githubusercontent.com/25627225/122166195-da2c5500-ceab-11eb-9211-94a8857cf4df.png)

**Comment by wumpz** [comment] 2021-06-16 07:16
The problem is in production `JoinerExpression`. Simple means a comma list of table names like

    select * from tab1, tab2

but in the grammar is no check when this `on` part is parsed, if there was a non simple join

    ( <K_ON> onExpression=Expression()  { join.setOnExpression(onExpression); })

So the solution should be a semantic Lookahead here with the check `!join.isSimple()`.

**Closed** 2021-09-06 11:34 UTC
Labels: bug
