### ISSUE TITLE
Support for MySQL user-defined variables with "@"

### ISSUE THREAD

**Issue by itwise-yjyoon** [JSQLParser/JSqlParser#152] opened 2015-07-17 09:37 UTC
# Using jsqlparser version
0.9

# Query
select date_format(date_add(now(), interval @dt_idx day), '%Y%m%d') as yyyymmdd_dt, 
@dt_idx := @dt_idx-1
from   metrics, (select @dt_idx := 1) dummy
limit  30

# Exception Message
net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 46.  Encountered: "d" (100), after : "@"
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:1750)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:9139)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_234(CCJSqlParser.java:8186)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_146(CCJSqlParser.java:8344)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_59(CCJSqlParser.java:8737)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_97(CCJSqlParser.java:8803)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_202(CCJSqlParser.java:8905)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_96(CCJSqlParser.java:8912)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_201(CCJSqlParser.java:8979)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_93(CCJSqlParser.java:5731)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_90(CCJSqlParser.java:5640)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_147(CCJSqlParser.java:5758)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_61(CCJSqlParser.java:5795)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_333(CCJSqlParser.java:7993)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_272(CCJSqlParser.java:8123)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_205(CCJSqlParser.java:8112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_103(CCJSqlParser.java:8152)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_134(CCJSqlParser.java:8625)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_59(CCJSqlParser.java:8711)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_97(CCJSqlParser.java:8803)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_202(CCJSqlParser.java:8905)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_96(CCJSqlParser.java:8912)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_201(CCJSqlParser.java:8979)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_93(CCJSqlParser.java:5731)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_90(CCJSqlParser.java:5640)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_147(CCJSqlParser.java:5758)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_61(CCJSqlParser.java:5795)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_272(CCJSqlParser.java:8120)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_205(CCJSqlParser.java:8112)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_103(CCJSqlParser.java:8152)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_134(CCJSqlParser.java:8625)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_59(CCJSqlParser.java:8711)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_97(CCJSqlParser.java:8803)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_202(CCJSqlParser.java:8905)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_96(CCJSqlParser.java:8912)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_201(CCJSqlParser.java:8979)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_93(CCJSqlParser.java:5731)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_90(CCJSqlParser.java:5640)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_147(CCJSqlParser.java:5758)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_61(CCJSqlParser.java:5795)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_70(CCJSqlParser.java:5989)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_378(CCJSqlParser.java:5921)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_341(CCJSqlParser.java:5962)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_296(CCJSqlParser.java:6079)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_235(CCJSqlParser.java:6549)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_150(CCJSqlParser.java:6089)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_67(CCJSqlParser.java:6304)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3_16(CCJSqlParser.java:6577)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_2_16(CCJSqlParser.java:5292)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:845)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:837)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:74)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:54)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)

**Comment by wumpz** [comment] 2015-07-17 10:27
Version 0.9.2 (https://github.com/JSQLParser/JSqlParser/tree/jsqlparser-0.9.2) introduced a first support for named uservariables. Did you try it with version >=0.9.2 or are you running a 0.9.0 release?
Cheers Tobias

**Comment by itwise-yjyoon** [comment] 2015-07-22 00:10
worked for me. thanks :) :+1:

**Comment by itwise-yjyoon** [comment] 2015-07-22 00:21
thanks for your rapid response :)
but I encountered another a exception message :(

# Test suite

    @Test
    public void testParse() throws JSQLParserException {
        String sql = "select date_format(date_add(now(), interval @dt_idx day), '%Y%m%d') as yyyymmdd_dt, \n" +
                "@dt_idx := @dt_idx-1 \n" +
                "from metrics, (select @dt_idx := 1) dummy \n" +
                "limit 30";
        Statement statement = CCJSqlParserUtil.parse(sql);
    }

# Exception message
...
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 19.
Was expecting one of:
    <EOF> 
    "AS" ...
    "DO" ...
    "ANY" ...
    "KEY" ...
    "PERCENT" ...
    "INTO" ...
    "FROM" ...
    "OPEN" ...
    "WHERE" ...
    "FOR" ...
    "XML" ...
...

**Comment by wumpz** [comment] 2015-07-22 05:06
At a first glance I would say the interval expression is the problem. At the moment JsqlParser does not recognize all possible constructs here.

**Comment by wumpz** [comment] 2015-08-24 13:50
Seems to be a duplicate of #165. Therefore I close this one.

**Closed by wumpz** 2015-08-24 13:50 UTC
