### ISSUE TITLE
[BUG] JSQLParser 4.8 : Postgres : Encountered unexpected token: "#>>"

### ISSUE THREAD

**Issue by sta-szek** [JSQLParser/JSqlParser#1950] opened 2024-01-25 10:04 UTC
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax_snapshot.html)

### Failing SQL Feature:
> Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "#>>" "#>>"

### SQL Example:
```
    @Query(
            value = """
                    SELECT json_object_agg(state, number) #>> '{}' as statistics, sum(h_o) as handledObjects
                    FROM (SELECT state, count(1) number, sum(objects) h_o
                    FROM some_table
                    WHERE xxxx = ?1
                    GROUP BY state) t;""",
            nativeQuery = true
    )
```

### Software Information:
- JSqlParser version 4.8 
- Database  PostgreSQL 15

### Tips:
Have no tips, the query seems to be valid in your online validator.

**Comment by manticore-projects** [comment] 2024-01-25 10:49
Greetings!

Unfortunately I can not reproduce your problem because:

1) JSQLParser parses and deparses it, [you can try online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsCsDOB7AdgfRQIwQUwGMAXDAQwHNyAKJI0ovAGljQFcBbbPAJwEoBiAHyCA5AG8AviNgBBYLFr0AlrSUEkAKHjbtzYByqwAFlli9Z8o6TQATADZ4bOfMU0AxAEoB5ALKxDsKAQMPCKDFo6kVHMkCisaESGAIxmLBxc3BFR2bB6BrDOhERIqSYoWZGevgoo7HgYdNgOFToA6gASIB4gsAAe-b2wALywAPxJLdoA4t4AqgAKsABCAJoKdAypRBoA3EA)

2) The AST clearly finds the JSonFunction

![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/14dba61c-5c7f-407b-8942-96b817de9b40)

You will need to share simple, self containing Java Test Code if you still have a concern.

**Comment by manticore-projects** [comment] 2024-01-30 17:47
Can I close this since there was not follow up and its working here?

**Closed** 2024-02-08 05:57 UTC
