### ISSUE TITLE
Failure to parse the Oracle select SQL that contains "not exists"

### ISSUE THREAD

**Issue by weijunlu1** [JSQLParser/JSqlParser#973] opened 2020-04-17 08:17 UTC
1.String sql = "select * from t001 t where not exists(select * from t002 t1 where t.c1=t1.c1 and t.c2=t1.c2 and ('241' in t1.c3||t1.c4))"
2.Statement statement = CCJSqlParserUtil.parse(sql);
3.Exception:
 Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "exists" "EXISTS"
    at line 1, column 32.
System
•Oracle
•java 1.8
•JSqlParser version 3.1

**Comment by wumpz** [comment] 2020-04-18 22:26
The problem is not "not exists" but this in expression without parenthesis. Using `in (t1.c3||t1.c4)` works fine.

**Comment by weijunlu1** [comment] 2020-04-20 03:37
@wumpz  That is true, thanks!

**Comment by wumpz** [comment] 2020-04-20 05:23
So can we close this? JSqlParser does not (yet) support this kind of construct.

**Comment by weijunlu1** [comment] 2020-04-20 05:57
Yes, you can close it, but it is for better to me if can support this construct.

**Comment by wumpz** [comment] 2020-04-24 11:10
Pull requests are welcome :)

**Closed** 2020-12-31 01:19 UTC
