### ISSUE TITLE
[BUG] JSQLParser Version : 4.6 parse simple sql error by \n

### ISSUE THREAD

**Issue by moodincode** [JSQLParser/JSqlParser#1822] opened 2023-07-07 10:55 UTC
String  sql1="select id ,  create_time\n" +
          "\n" +
          "\n" +
          "         \n" +
          "\n" +
          "        FROM " +
          "         test \n" +
          "         \n" +
          "         WHERE  id = ?";
        try {
            CCJSqlParserUtil.parse(sql1);
        } catch (JSQLParserException e) {
           e.printStackTrace();
        }

net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FROM" "FROM"
    at line 6, column 9.

Was expecting:

    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.moodincode.qywork_notice.TestSqlParser.main(TestSqlParser.java:23)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "FROM" "FROM"

**Comment by moodincode** [comment] 2023-07-07 10:58
that sql generate by mybatis xml grammar

**Comment by manticore-projects** [comment] 2023-07-07 11:09
2 empty lines terminate a statement. Its a feature but not a bugOn 7 Jul 2023 17:58, moodincode ***@***.***> wrote:
that sql generate by mybatis xml grammar

**Comment by manticore-projects** [comment] 2023-07-07 11:10
Tell mybatis to fix there code as there is no good reason to have 2 or more empty lines in a sql statement On 7 Jul 2023 17:58, moodincode ***@***.***> wrote:
that sql generate by mybatis xml grammar

**Comment by amigalev** [comment] 2023-07-17 11:03
> 2 empty lines terminate a statement. Its a feature but not a bugOn 7 Jul 2023 17:58, moodincode ***@***.***> wrote: that sql generate by mybatis xml grammar —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Is it a feature of JSqlParser or some SQL dialect? In my project I've written workaround to delete "\n\n\n" from SQL queries before parsing them. Because I have too many queries from different sources

**Comment by manticore-projects** [comment] 2023-07-18 02:04
It's a feature of JSQLParser since we can parse and split many statements from a text.
There is simply no good reason why any SQL Statement should contain more than 1 empty line and MyBatis seems to be the only producer (why exactly please?)

At the same time, a SQL Editor will typically look like this:
```
select 1


select 2


select 3
```

**Comment by amigalev** [comment] 2023-07-18 05:57
> It's a feature of JSQLParser since we can parse and split many statements from a text. There is simply no good reason why any SQL Statement should contain more than 1 empty line and MyBatis seems to be the only producer (why exactly please?)
> 
> At the same time, a SQL Editor will typically look like this:
> 
> ```
> select 1
> 
> 
> select 2
> 
> 
> select 3
> ```

Thank you for your answer.

I agree with you that there is no reasons to use the multiple line separators. In my situation, I have a huge count of SQL queries and some of them contains ."\n\n\n" (historicaly). I haven't access to all of them, because we have many subprojects where the queries are stored. This is the reason I've written workaround to delete the reduntant separators and I hope we will delete them in the future

**Comment by manticore-projects** [comment] 2023-07-23 02:32
Closing, since no further questions has been asked.

**Closed by manticore-projects** 2023-07-23 02:32 UTC
