### ISSUE TITLE
Exception thrown when parentheses surrounds a table in the FROM clause

### ISSUE THREAD

**Issue by tomershay** [JSQLParser/JSqlParser#559] opened 2017-12-27 08:52 UTC
The following query is valid (at least in MySQL), but an exception is thrown when trying to parse it.
``SELECT col from (`table1`)``
It seems that the same issue occurs for multiple tables as well:
``SELECT col from (`table1`), (`table2`)``

**Comment by wumpz** [comment] 2017-12-27 12:52
I don't know the issue but this seems to be a duplicate.

**Comment by sh-tomer** [comment] 2017-12-27 13:30
@wumpz, duplicate of which issue?

**Comment by wumpz** [comment] 2021-01-03 00:28
JSqlParser 4.0 parses this.

**Closed by wumpz** 2021-01-03 00:28 UTC
