### ISSUE TITLE
`= BINARY ` AND `LIKE BINARY` are not support

### ISSUE THREAD

**Issue by lastmayday** [JSQLParser/JSqlParser#595] opened 2018-03-26 09:13 UTC
### Actual Behavior

```java
String sql = "SELECT Name FROM T_User WHERE Name = BINARY 'test' OR Name LIKE BINARY 'test-%'";
Statement stmt = CCJSqlParserUtil.parse(sql);
```

When I ran these code, I got an exception:
```
net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:56)
	at org.lastmayday.example.parser.JSqlParser.main(JSqlParser.java:23)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "=" "= "" at line 1, column 36.
Was expecting one of:
    <EOF> 
    "AND" ...
    "FOR" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "HAVING" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "ORDER" ...
    "ORDER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 1 more
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "=" "= "" at line 1, column 36.
Was expecting one of:
    <EOF> 
    "AND" ...
    "FOR" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "HAVING" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "ORDER" ...
    "ORDER" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	at org.lastmayday.example.parser.JSqlParser.main(JSqlParser.java:23)
```

But if I remove the `BINARY`, it works well.

```java
String sql = "SELECT Name FROM T_User WHERE Name = 'test' OR Name LIKE 'test-%'";
Statement stmt = CCJSqlParserUtil.parse(sql);
```

### Expected Behavior

No exception.

### Specifications

  - Version: 
```xml
<dependency>
    <groupId>com.github.jsqlparser</groupId>
    <artifactId>jsqlparser</artifactId>
    <version>1.1</version>
</dependency>
```
  - Platform: jdk1.8.0_144
  - Subsystem:

**Comment by manticore-projects** [comment] 2021-10-19 14:22
Postgres implicit casts are not supported. Explicit casts will work fine.
Duplicate of #1344.

**Closed** 2023-09-06 07:58 UTC
Labels: duplicate
