### ISSUE TITLE
CCJSqlParserUtil.parse(originalSql); if the sql has LIKE '%'||?||'%' ,   then it throw exception 

### ISSUE THREAD

**Issue by SixGodloop** [JSQLParser/JSqlParser#1087] opened 2020-12-22 03:15 UTC
**Describe the bug**
I use the mybatis, and My sql in xml is  select count(*) from table o where 1=1 AND O.field1 LIKE '%'||?||'%' AND O.filed2 = ?
so I use the  CCJSqlParserUtil.parse(originalSql); to parse my sql, but it throw exception

**To Reproduce**
1. select count(*) from table o where 1=1 AND O.field1 LIKE '%'||?||'%' AND O.filed2 = ?
2. CCJSqlParserUtil.parse(originalSql); 
3. Exception

**Expected behavior**
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
... 121 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "||" <OP_CONCAT>
at line 21, column 37.
&"
"&&"
")"
"::"
"<<"
">>"
"AND"
"CONNECT"
"ESCAPE"
"EXCEPT"
"FOR"
"GROUP"
"HAVING"
"INTERSECT"
"MINUS"
"ORDER"
"START"
"UNION"
"^"
"|"

    at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:19398)
    at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:19248)
    at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:4628)
    at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3185)
    at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3351)
    at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3059)
    at net.sf.jsqlparser.parser.CCJSqlParser.SubSelect(CCJSqlParser.java:9738)
    at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:4556)
    at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:3185)
    at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3351)
    at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:3059)
    at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:3052)
    at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:132)
    at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:83)
    at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)

Was expecting one of:
**System**
 - Oracle
- Java 1.8
- com.github.jsqlparser jsqlparser 1.4

**Comment by wumpz** [comment] 2020-12-30 21:35
The problem is that your *||?||* does not contain any whitespaces. Since JSqlParser tries to support different database dialects and therefore other operators, here is a collision. *?|* will be recognized as a JSON parameter for Postgresql. 

So there is no grammar change solution for JSqlParser at hand.

**Comment by wumpz** [comment] 2021-01-13 19:09
So can we close this?

**Closed** 2021-01-13 23:57 UTC
