### ISSUE TITLE
Parser fails if column name is synonym

### ISSUE THREAD

**Issue by salonijuneja** [JSQLParser/JSqlParser#1211] opened 2021-05-25 09:53 UTC
Parser failed with JSQLParserException if a column name in select statement is synonym.
eg: select businessDate as "bd", synonym as "synonym" from sc.tab

**Comment by manticore-projects** [comment] 2021-05-25 11:06
On Tue, 2021-05-25 at 09:53 +0000, salonijuneja wrote:
> select businessDate as "bd", synonym as "synonym" from sc.tab

It is NOT about the alias, but about the unquoted column name:


"synonym" is a Keyword and you can't use that without quotes.
Please close the issue, when confirmed.

Best regards
Andreas

**Comment by manticore-projects** [comment] 2021-05-25 11:07
It is NOT about the alias, but about the unquoted column name:

![image](https://user-images.githubusercontent.com/18080123/119487825-0a3c7880-bd84-11eb-9b84-9a8b2493d8b2.png)

"synonym" is a Keyword and you can't use that without quotes.
Please close the issue, when confirmed.

Best regards
Andreas

**Comment by salonijuneja** [comment] 2021-05-25 11:52
But this query (without quotes) executes successfully without error on Database (Sybase IQ though)

**Closed** 2021-05-25 21:50 UTC

**Comment by wumpz** [comment] 2021-05-25 21:53
@manticore-projects To allow keywords as object names you could include those in `RelObjectNameWithoutValue`. In some cases this is not possible because the conflicts in JSqlParser grammar would be to huge to tackle, but this `synonym` keyword made no problems.
