### ISSUE TITLE
AST convert error

### ISSUE THREAD

**Issue by coderstory** [JSQLParser/JSqlParser#1399] opened 2021-11-04 07:04 UTC
**Describe the bug**
 AST convert error

**To Reproduce**
1. select CONVERT(true, CHAR)
2. Parsing this SQL using JSqlParser with this statements
3. ![企业微信截图_16360091343109](https://user-images.githubusercontent.com/11525359/140271045-9755266c-0d2a-4d40-aed4-f95608a66adc.png)

**Expected behavior**
 why  the key [true] and [Char]  is  instance of Column

**System**
 - Database you are using
  mysql8.0
- Java Version
  11
- JSqlParser version
  4.2

**Comment by manticore-projects** [comment] 2021-11-04 10:40
Greetings.

Your observation is not a dogmatic bug, but a practical feature: JSQLParser is agnostic to the RDBMS (to a large extend) and does not even try to understand the specific syntax but will parse the syntax as generic as possible.

So in your case, JSQLParser does not see a specific `CONVERT` function with a `Boolean` and a `CHAR typename`. Instead it sees any abstract function and `true` could be a column-name and `char` could be a column name.

We do not know better and we do not WANT to know better -- because this would be expensive (parsing and implementation wise) and would restrict us to a certain RDBMS.

So as a rule of thumb: JSQLParser will always try to parse you statement as simple as possible and assign the "first compliant java class" (in the order of parsing effort).

Related to your example, we test first if `true` and `char` could be a column. When then answer is yes, we are satisfied and move on and do not even (want to) try if it also could be a `BOOL expression` or a `CHAR typename`. 

If you are looking for RDBMS specific grammar which would return `CONVERT function` and `EXPRESSION` and `TYPENAME` then you may have more luck with ANTLR and its various RDBMS specific grammars (which all use different tokens and productions and are huge and complex and slow.)

**Comment by manticore-projects** [comment] 2021-11-04 10:41
@wumpz: I tend to close this as "not a bug but a feature", how do you see it please?

**Comment by wumpz** [comment] 2021-11-19 20:42
It's exactly like you lectured ;). The true nature of objects or values parsed could only be revealed using an actual running database.

**Closed by wumpz** 2021-11-19 20:42 UTC
