### ISSUE TITLE
JSqlParser  cann't parser sql correctly

### ISSUE THREAD

**Issue by sixtrees** [JSQLParser/JSqlParser#250] opened 2016-04-23 02:30 UTC
I use JSqlParser to parser user'sql , when user input a sql ,such as select * from tabl1 "tabl1(city)"，it will meet a exception.

**Comment by wumpz** [comment] 2016-04-23 08:46
Please provide the concrete exception. Tobias

**Comment by mlkammer** [comment] 2016-04-25 14:20
Cannot reproduce the exception. The following code works:
`CCJSqlParserUtil.parse("select * from tabl1 \"tabl1(city)\"");`

**Comment by wumpz** [comment] 2016-04-25 15:06
@mlkammer Thx for testing it. 

So could we close this issue or are there more informations?

**Closed** 2016-05-16 12:45 UTC
