### ISSUE TITLE
With with values list doesn't parse.

### ISSUE THREAD

**Issue by Intektor** [JSQLParser/JSqlParser#1135] opened 2021-03-21 21:05 UTC
**Describe the bug**
Using as (values ...) in a with doesn't parse.

**To Reproduce**
```sql
           with sample_data(day, value) as (values (0, 13), (1, 12), (2, 15), (3, 4), (4, 8), (5, 16))
            
           select day, value from sample_data
```

```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "," ","
    at line 1, column 49.

Was expecting one of:

    ")"
    "EXCEPT"
    "INTERSECT"
    "MINUS"
    "ORDER"
    "UNION"

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:165)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:59)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:37)`
```

I tested the code on hyperdb, postgresql and sqlite and it works there.

**System**
- java: 8
- version: 4.0

**Comment by wumpz** [comment] 2021-04-10 20:43
Thats right. This feature is not supported. PRs are welcome. 

At the moment a values construct is only allowed as a from part like:

```sql
SELECT * FROM (VALUES (1, 2), (3, 4)) AS test
```

Within the grammar file at `SingleStatement()` there a new statement type for **values** has to be integrated.

**Comment by milnev** [comment] 2021-04-15 10:22
WITH supports only SELECT now, whats about INSERT/UPDATE/DELETE?
https://www.postgresql.org/docs/9.1/queries-with.html
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "UPDATE" "UPDATE"

**Comment by manticore-projects** [comment] 2021-04-18 12:13
No promise, but I will try to look into that.

**Comment by manticore-projects** [comment] 2021-04-24 09:10
> WITH supports only SELECT now, whats about INSERT/UPDATE/DELETE?
> https://www.postgresql.org/docs/9.1/queries-with.html
> Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "UPDATE" "UPDATE"

ONLY this is fixed in #1178.
`WITH ... (value_list)` is still open.

**Comment by manticore-projects** [comment] 2021-05-07 01:43
This is just a not to myself on a H2 supported example. Please more careful about column names next time.

```sql
CREATE TABLE sample_data (
    "DAY"        INT
    , "VALUE"    INT
)
;

with sample_data("DAY", "VALUE") as (values ((0, 13), (1, 12), (2, 15), (3, 4), (4, 8), (5, 16)))
select "DAY", "VALUE" from sample_data;

with sample_data("DAY", "VALUE") as (values (0, 13), (1, 12), (2, 15), (3, 4), (4, 8), (5, 16))
select "DAY", "VALUE" from sample_data;

with sample_data("DAY") as (values 0, 1, 2)
           select "DAY" from sample_data;
```

**Comment by manticore-projects** [comment] 2021-05-07 02:18
I got it partially working when VALUES() is followed by brackets:
```java
@Test
  public void testWithWithValueList1135_SimpleExpressions() throws JSQLParserException {
    assertSqlCanBeParsedAndDeparsed(
        "with sample_data(\"DAY\") as (values (0, 1, 2))\n" +
"           select \"DAY\" from sample_data",
        true);
  }

  @Test
  public void testWithWithValueList1135_MultiExpressions() throws JSQLParserException {
    assertSqlCanBeParsedAndDeparsed(
        "with sample_data(\"DAY\", \"VALUE\") as (values ((0, 13), (1, 12), (2, 15), (3, 4), (4, 8), (5, 16)))\n" +
"select \"DAY\", \"VALUE\" from sample_data",
        true);
  }
```
Unfortunately H2 also accepts the version without the Brackets after VALUES and I am at loss how to make that happen.

**Comment by manticore-projects** [comment] 2021-05-07 03:59
There is a also the Problem, that ValuesStatement does not recognise, if there were Brackets or not. Both versions deparse into "without brackets". 

So I will leave it as a [Working PoC](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20LTAEGUEkFkAUBkCipEA1YCVHigeQHKjyTgAqoA6pKQBKgBCGAggMIDSip4AUFbaAGcAhgFsADgBsApgH0AJkIAuQ0AApQAIgAiTAJobQASlBNwa7qEtXLANSbwAqtjWgADABpQARk8AmI0bc4IhILOTaehrcAGIYuNCCopKyCsrcANzcWSCg0A7wpJAIyGiY2HiExGSU1HSMrBxcvLWJ4tLySirqmjr6FtYDg9aeGnaOiAbGpuZDoGNOZt2Wqh7eAMyGnqo+3r6bar6eXgCshv2zF6Bba54ALPuqt54AHA-HRwBsxt9BIYhhlgifVmI3mExicQSwjaKU6GSAA+) for the moment.

As soon as my other PR is accepted, I can commit these changes and then maybe @wumpz will help me to sort these Brackets.

**Comment by manticore-projects** [comment] 2021-05-10 03:29
This issue is much more complex than I thought because the following is a valid statement:
```sql
-- testComplexWithQueryIssue561()
WITH split (    word
                , str
                , hascomma ) AS (
        VALUES ( '', 'Auto,A,1234444', 1 )
        UNION ALL
        SELECT  Substr( str, 0, CASE
                        WHEN Instr( str, ',' )
                            THEN Instr( str, ',' )
                        ELSE Length( str ) + 1
                    END )
                , Ltrim( Substr( str, Instr( str, ',' ) ), ',' )
                , Instr( str, ',' )
        FROM split
        WHERE hascomma )
SELECT Trim( word )
FROM split
WHERE word != ''
;
```
For this statement, the Parser catches a `SubSelect` consisting of a `ValuesStatement` and a `Select`.
It appears to me that `ValuesStatement` supports only `SimpleExpressionList`:
```javacc
ValuesStatement Values(): {
    List<Expression> expList = new ArrayList<Expression>();
    Expression exp;
} {
    <K_VALUES>
    "("
        exp=PrimaryExpression() { expList.add(exp); }
                        ("," exp=PrimaryExpression()  { expList.add(exp); } )*
    ")"
    {
        return new ValuesStatement(expList);
    }
}
```

This is a challenge because (without a major rewrite) we need to distinguish now at least 4 use cases: 

1) SimpleExpressionList using Brackets '(VALUES ('a', 'b', 'c')) parsed as `SubQuery` already (works)
2) SimpleExpressionList without Brackets '(VALUES 'a', 'b', 'c') parsed as `MultiExpressionList` (works)
3) MultiExpressionList using Brackets '(VALUES (('a', 'b', 'c'), ('a', 'b', 'c'))) parsed as `MultiExpressionList` (works)
4) MultiExpressionList without Brackets '(VALUES ('a', 'b', 'c'), ('a', 'b', 'c')) parsed as `MultiExpressionList` (fails, because it competes with case 1 parsed as `SubQuery`

Case 4 is never caught because it will trigger Case 1 before (and fail there because `ValuesStatement` does not support `MultiExpressionList`). Unfortunately we need to check for Case 1 first or else we break the UNION statement shown above.

In my limited understanding, there are 2 possible solutions:
a) write a Grammar, which triggers case 1 ONLY IF case 4 did not apply. (I tried that but did not succeed to write a valid IF NOT construct in JavaCC)
b) OR refactor `ValuesStatement` so it supports `MultiExpressionList` and then refactor also the `WithItem` so it has an `ItemsList` (implemented by `SubSelect` or `SimpleExpressionList` or `MultiExpressionList`) instead of a SubSelect

I am scared that b) would break too much stuff and introduces to many unwarranted changes.
But I would need a bit of help to get a) working (with a IF NOT `MultiExpressionList without Brackets` logic)

**Comment by manticore-projects** [comment] 2021-05-10 07:26
Well, after a lot of back and forth, I have solved it.
[Formatted SQL Preview](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20LTAEGUEkFkAUBkCipEA1YCVHigeQHKjyTgAqoA6pKQBKgBCGAggMIDSip4AUFbaAGcAhgFsADgBsApgH0AJkIAuQ0AApQAIgAiTAJobQASm6hToJuDWgAak3gBVbFYAMAGlABGdwCYjR7uCISCzk2noa3ABiGLjQgqKSsgrK3ADc3NwgoND28KSQCMhomNh4hMRklNR0jKwcXLzV8eLS8koq6mH67hq2DogGxmbmlup9jqNmqm6eAMyG7qpent4Lat7uHgCsQ8N7+8OLs+4ALGuqJ+4AHOdbmwBshn7GgcHkmjr6Jgc94wNRMTiwhaSXaaQyWSgcCQKHQWBwkAIRBI5D4NFw9nItXYnB4aOaiTayisXUG31MFisf0sM2WvheQUQIQ+4QBsQJrWSQnBmTAOTyBRhxXhZWRlTRGKxzBxDXxwMJXJJnw0vzsjjJw0pYzVTnUtNm-gORtAi2WHnp5ONh3Wmy2hqteyOp3tDrMi0uoCuLtdJrUd0892eAUZzJZXyNqv6EWi7PlnLB6V5Nh1YvI9nwiMIryZpEa-AEkgAloorGYAO4AewATnJLa73AJFFW6w73AALIQCADGFZEIhUTy1LdM1KsAHIx+4x0wAK6KCuuJiuc2zE5rk6Tzze4bpzPmeDwYcQEPvcAzgBGjar6iv7hmLAsiCPPrMFBoiEIkAAdleb02p64Y7bi+xq0B+oDfr+gj-qAk5AbsIEHEEgREFIX4AOaKG2f5Vn4ADUnjPg6H5aMBVruPATaFiI6hnpeTY4e4kEMdBVYAfBRjsWRxpMT+LG3rBgHcTGQJFooR5vogWCgB23a9v2-jZsypBVtR6iVjW-giYIYm8O+0kaXIoAAIQALywWOaRAA+) is available including patched JSQLParser-4.1 Snapshot Binary.

I have implemented Solution a) checking first, if there is a `SimpleExpressionList` or `MultExpressionList` WITHOUT brackets. If so, parse as ExpressionList, else parse as SubQuery.
```
<K_AS>
    // if the next block looks alike an ExpressionList without Brackets, then parse as List
    ( LOOKAHEAD( "(" <K_VALUES> (SimpleExpressionList() | MultiExpressionList()) ")" ) 
        "(" <K_VALUES>
            
        // decide what kind of List to parse
        ( LOOKAHEAD( MultiExpressionList() ) 
            ( multExpressionList =  MultiExpressionList() { with.withUseBracketsForValues(false).setItemsList(multExpressionList); } )
            | ( simpleExpressionList = SimpleExpressionList() { with.withUseBracketsForValues(false).setItemsList(simpleExpressionList); } ))
            
        ")"

    // Otherwise parse it as a SubSelect
        | "(" select = SubSelect() { with.setSubSelect(select.withUseBrackets(false)); with.setUseValues(false); } ")"
            
    )

**Comment by wumpz** [comment] 2021-05-10 21:18
So the **values** thing is already a statement. Had totally forgotten this. So this statement works as well:

    with sample_data(day, value) as (values ((0, 13), (1, 12), (2, 15), (3, 4), (4, 8), (5, 16))) select day, value from sample_data

**Comment by wumpz** [comment] 2021-05-17 07:41
As I understood your PR, it is still so huge, you change directly the **withitem** production. As I mentioned this is not needed. I will build a change using only the ValueStatement. Hope I will get to this today.

**Comment by manticore-projects** [comment] 2021-05-17 08:32
On Mon, 2021-05-17 at 00:42 -0700, Tobias wrote:
> As I mentioned this is not needed. I will build a change using only
> the ValueStatement. Hope I will get to this today.

Ok, what ever works.
But please be aware, that the PR addressed 2 different issues:

a) Nested WITH statements and
b) ValueList in WITH statements (without additional brackets)

Best regards
Andreas

**Comment by manticore-projects** [comment] 2021-06-03 06:08
Can we close this now? It has been resolved and tested.

**Comment by wumpz** [comment] 2021-06-06 12:10
Sure. I forgot. You already included those with statements in another PR.

**Closed by wumpz** 2021-06-06 12:10 UTC
