### ISSUE TITLE
[BUG] The TablesNamesFinder mistakenly treat nested SELECT in FROM as table

### ISSUE THREAD

**Issue by pinkfloyda** [JSQLParser/JSqlParser#1987] opened 2024-04-08 05:01 UTC
Recently I used TablesNamesFinder trying to find true tableNames within a SQL query, during testing, found out it treat nested SELECT alias as table, which is wrong.

Sample query

```
select * from (select * from a) as a1, b
select * from b, (select * from a) as a1
```

It calculates `a, a1, b` are the table names, a1 suppose to be an alias, not a table name

I used two examples, as I found out the parsed structure of these two examples are slight different that the 1st case, the a1 alias shown within `plainSelect.fromItem.alias`. And 2nd case, the a1 alias shown within  one of `plainSelect.joins`'s `fromItem.alias`.

Is that normal or expected?

**Comment by manticore-projects** [comment] 2024-04-08 07:05
Greetings,

although it seems reasonable to exclude any Aliases from the returns, `TableNamesFinder` will always be more like a `Find any Object Names suspiciously looking like a Table` and you are supposed to filter the returned list against the actual Meta Data.

Because:
```
with a (select 1 b from b)
select b from a
;
```

**Comment by manticore-projects** [comment] 2024-04-08 23:57
This test succeeds against JSQLParser 4.10 Snapshot and will likely succeed against 4.9 or 4.8 since nothing has been changed in this regard:

```java

    @Test
    void testSubqueryAliasesIssue1987() throws JSQLParserException {
        String sqlStr = "select * from (select * from a) as a1, b;";
        Set<String> tables = TablesNamesFinder.findTablesOrOtherSources(sqlStr);
        assertThat(tables).containsExactly("a", "b");
        assertThat(tables).doesNotContain("a1");

        sqlStr = "select * from b, (select * from a) as a1";
        tables = TablesNamesFinder.findTablesOrOtherSources(sqlStr);
        assertThat(tables).containsExactly("a", "b");
        assertThat(tables).doesNotContain("a1");
    }
```

Please reproduce and then close this issue.

**Comment by pinkfloyda** [comment] 2024-04-09 02:47
Sorry, my example is bad, as it later must reference the alias in FROM clause, below SQL will reproduce it

```
SELECT * FROM b, (SELECT * FROM a) as a1 WHERE b.id IN ( SELECT id FROM a1 )
```

It will output a1, a, b as tableNames.

The reason my earlier example works is because there is no reference to the alias, a1 not at all tracked, but for withStatement it is tracked, but only in https://github.com/JSQLParser/JSqlParser/blob/master/src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java#L284, it don't really track nested query alias

**Comment by manticore-projects** [comment] 2024-04-09 07:20
This is exactly what I have tried to explain at first: there are situations where the AST alone is not sufficient and you will need to add Meta Data information and/or need to operate with actual name scopes within the AST.

**Comment by manticore-projects** [comment] 2024-04-09 07:27
Please more thoroughly with your tests because your example is still working fine and as expected (with 4.10-Snapshot at least):

```java
    @Test
    void testSubqueryAliasesIssue1987() throws JSQLParserException {
        String sqlStr = "WITH a2 AS (SELECT * FROM a) SELECT * FROM b WHERE b.id IN ( SELECT id FROM a2 )";
        tables = TablesNamesFinder.findTablesOrOtherSources(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a", "b", "a2");

        tables = TablesNamesFinder.findTables(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a", "b");
        assertThat(tables).doesNotContain("a2");
        ;
    }
```

**Closed** 2024-04-09 08:17 UTC

**Comment by manticore-projects** [comment] 2024-04-09 08:20
I have removed any `Alias` of any `ParenthesedSelect`, `ParenthesedFromItem`, `LateralSubSelect` and `WithItem`.
This eases the problem for simple AST with only one scope, although it would not completely solve it and even may harm some other cases. Its probably good for 95% of the use cases, we will see.

The following test passes now:

```java
    @Test
    void testSubqueryAliasesIssue1987() throws JSQLParserException {
        String sqlStr = "select * from (select * from a) as a1, b;";
        Set<String> tables = TablesNamesFinder.findTablesOrOtherSources(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a", "b", "a1");

        tables = TablesNamesFinder.findTables(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a", "b");
        assertThat(tables).doesNotContain("a1");

        sqlStr = "select * from b, (select * from a) as a1";
        tables = TablesNamesFinder.findTablesOrOtherSources(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a1", "a", "b");

        tables = TablesNamesFinder.findTables(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a", "b");
        assertThat(tables).doesNotContain("a1");

        sqlStr = "SELECT * FROM b, (SELECT * FROM a) as a1 WHERE b.id IN ( SELECT id FROM a1 )";
        tables = TablesNamesFinder.findTablesOrOtherSources(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a1", "a", "b");

        tables = TablesNamesFinder.findTables(sqlStr);
        assertThat(tables).containsExactlyInAnyOrder("a", "b");
        assertThat(tables).doesNotContain("a1");
    }
```

**Comment by pinkfloyda** [comment] 2024-04-09 15:22
Yeah, I am about to think the same, but majorly in tracking PlainSelect's fromItem and Join's fromItem. And got same issues if got tableName, alias clash. But I think a clash is not a formal SQL syntax? But anyway, I agree your fix will cover 95% of cases
