### ISSUE TITLE
limit / offset should auto try cast to int

### ISSUE THREAD

**Issue by sixinli** [JSQLParser/JSqlParser#1376] opened 2021-10-15 17:47 UTC
**Describe the bug**

**To Reproduce**
1. `select 1 offset '0'`
2. Parsing this SQL using JSqlParser with this statements
3. Exception
```
org.junit.ComparisonFailure: Expected query to parse but it failed to parse (error: Encountered unexpected token: "\'0\'" <S_CHAR_LITERAL>
    at line 1, column 19.
```

**Expected behavior**
query to parse fine

**System**
 - postgres
- Java 11
- JSqlParser 4.2

**Comment by wumpz** [comment] 2021-10-15 23:25
Character literals are not allowed as parameter there. Using an integer should do fine.

**Comment by manticore-projects** [comment] 2021-10-16 03:33
Duplicate of #933

**Closed as completed** 2021-10-20 21:05 UTC
Labels: duplicate
