### ISSUE TITLE
Parsing "SELECT COUNT(IF(s_sheet_status IN ('10','30'),TRUE,NULL))" throws exception

### ISSUE THREAD

**Issue by yaox0017** [JSQLParser/JSqlParser#1310] opened 2021-08-24 09:18 UTC
Parser failing on query:

SELECT COUNT(IF(s_sheet_status IN ('10','30'),TRUE,NULL)) FROM con_pur_contract;

Version：
com.github.jsqlparser
jsqlparser
4.1

Error info :
`
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 13.

Excuse me, is this the problem I use？

**Comment by manticore-projects** [comment] 2021-08-24 23:54
Duplicate of #1284, 4.2-SNAPSHOT does solve the problem.

**Closed by manticore-projects** 2021-08-24 23:54 UTC

**Comment by yaox0017** [comment] 2021-08-25 02:41
thanks!
