### ISSUE TITLE
Missing Oracle-flavor multiple drop column case

### ISSUE THREAD

**Issue by ashleycoxley** [JSQLParser/JSqlParser#1363] opened 2021-10-11 21:27 UTC
Thanks for the great parser. I noticed that it's missing support of the Oracle way to drop multiple columns in a single statement. Here's the Oracle syntax to drop multiple columns ([source](https://oracle-base.com/articles/8i/dropping-columns)):

ALTER TABLE [schema].[table] DROP COLUMN ([col1], [col2]);

When parsing, it throws this error: 

> Encountered unexpected token: "(" "("
>     at line 1, column 31.
> 
> Was expecting one of:
> 
>     "COLUMN"
>     "CONSTRAINT"
>     "INDEX"
>     <S_IDENTIFIER>
>     <S_QUOTED_IDENTIFIER>

Java version 8, JSqlParser version 4.2

**Comment by manticore-projects** [comment] 2021-10-11 23:49
Thank you for reporting, its a Duplicate of #1245.

**Comment by manticore-projects** [comment] 2021-10-18 03:38
Should be fixed, but please verify your example.
According to https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_3001.htm#i2103683 you can have
1) Single Column Drop using the `COLUMN` keyword or
2) Multi Column Drop without the `COLUMN` keyword

So you example would still fail, but the following will work:
```sql
ALTER TABLE foo DROP (bar, baz) CASCADE;
```

Do let me know any issues or concerns.

**Closed** 2021-10-20 21:01 UTC
Labels: duplicate
